<a href="https://colab.research.google.com/github/rajalokar/AI_image_Captioning_project/blob/main/Tutorial_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [84]:
import numpy as np

In [85]:
# Initializing and printing array
arr = np.array([[3,6,7]])
arr

array([[3, 6, 7]])

In [86]:
# Printing an array by index
print(arr[0,1])

6


In [87]:
# Printing the shape of an array
arr.shape

(1, 3)

In [88]:
# Printing the size of an array
arr.size

3

In [89]:
# Printing the data type stored inside that array
arr.dtype

dtype('int64')

In [90]:
# Array by its location
arr[0,1]

np.int64(6)

In [91]:
# Changing the value of an array by index
arr[0,1] = 6
arr

array([[3, 6, 7]])

In [92]:
ar = np.array([[1,2,3],
       [4,5,6],
       [7,1,0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [93]:
ar.dtype

dtype('int64')

In [94]:
ar.shape

(3, 3)

In [95]:
ar.size

9

In [96]:
ar
ar[1,0]

np.int64(4)

In [97]:
ar[1,0] = 6
ar

array([[1, 2, 3],
       [6, 5, 6],
       [7, 1, 0]])

In [98]:
a = np.zeros([2,4],int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [99]:
b = np.ones([2,4],int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [100]:
range = np.arange(10)
rang = np.arange(2,10)
ran = np.arange(2,10,2)
print(range)
print(rang)
print(ran)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [101]:
lin = np.linspace(0,10,6)
lin

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [102]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [103]:
emp_lin = np.empty_like(lin)
emp_lin

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [104]:
ide = np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [105]:
ide.shape

(10, 10)

In [107]:
ab =np.arange(99)
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [114]:
ab = ab.reshape(3,33)
ab

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [118]:
ab = ab.ravel()
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [119]:
print(type(ab))

<class 'numpy.ndarray'>


# Axis

In [121]:
X = np.array([[1,2,3],
       [4,5,6],
       [7,1,0]])

X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [123]:
X.sum(axis = 0)

array([12,  8,  9])

In [124]:
X.sum(axis = 1)

array([ 6, 15,  8])

In [130]:
x = X.T
x

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [131]:
x.sum(axis = 0)

array([ 6, 15,  8])

In [132]:
x.sum(axis=1)

array([12,  8,  9])

In [133]:
ar.flat

In [134]:
for i in x.flat:
    print(i)

1
4
7
2
5
1
3
6
0


In [137]:
arr.ndim

2

In [138]:
x.nbytes

72

In [141]:
one = np.array([1,3,4,634,2])
one.argmax()


np.int64(3)

In [142]:
one.argmin()


np.int64(0)

In [143]:
one.argsort()

array([0, 4, 1, 2, 3])

In [151]:
x

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [145]:
x.argmin()

np.int64(8)

In [146]:
x.argmax()

np.int64(2)

In [147]:
x.argsort()

array([[0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]])

In [149]:
x.argmax(axis=0)

array([2, 2, 0])

In [150]:
x.argmax(axis=1)

array([2, 1, 1])

In [154]:
x.ravel()

array([1, 4, 7, 2, 5, 1, 3, 6, 0])

In [166]:
x+X

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [165]:
X*x

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [168]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [167]:
np.sqrt(X)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [170]:
x.sum()

np.int64(29)

In [171]:
x.min()

np.int64(0)

In [172]:
x.max()

np.int64(7)

In [173]:
np.where(x>5)

(array([0, 2]), array([2, 1]))

In [174]:
type(np.where(x>5))

tuple

In [176]:
np.count_nonzero(x)

8

In [177]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [178]:
import sys

In [179]:
py_ar = [4,5,6,7]

In [180]:
np_ar = np.array(py_ar)

In [181]:
sys.getsizeof(1) * len(py_ar)

112

In [185]:
np_ar.itemsize * len(np_ar)

32